### ISSUE TITLE
Error when parsing api response

### ISSUE THREAD

**Issue by slugo** [23/node-23video#7]
Hi, we've been using this library for a couple of months, but suddenly it stopped working. Right now  we're using the library like this:

```
var vp = require('node-23video')(vpUrl, vpKey, vpSecret);
const response = await vp.photo.getUploadToken({ ... })
                            .then(response=> ...);
```
which makes a request to `/api/photo/get-upload-token`, but now we always get the following error:
`JSON parse error SyntaxError: Unexpected token o in JSON at position 1`.

 We're thinking maybe the response format from the api has changed, but it's not reflected in the library.

**Comment by steffentchr** [comment]
This issue was caused by a change in response types, which caused issues with Restler. The issue has been resolved server-side.
